import { DEVICE_TYPE_VALUES, type Device } from "@/lib/state/types";

const AUTO_NAME_PATTERN = new RegExp(
  `^(?:${[...DEVICE_TYPE_VALUES, "device"].join("|")})-\\d+-\\d+-\\d+-\\d+$`,
);
const SLUG_ONLY_PATTERN = /^[a-z0-9-]+$/;
const APPLE_GENERIC_NAME_PATTERN = /^apple device \(([^)]+)\)$/i;

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function ipSlug(ip: string): string {
  return ip.trim().toLowerCase().replaceAll(".", "-").replaceAll(":", "-");
}

export function isAutoGeneratedDeviceName(name: string, ip: string): boolean {
  const normalized = name.trim().toLowerCase();
  if (!normalized) {
    return true;
  }

  const dashedIp = ipSlug(ip);
  if (normalized === ip.trim().toLowerCase() || normalized === dashedIp) {
    return true;
  }

  if (AUTO_NAME_PATTERN.test(normalized)) {
    return true;
  }

  const appleGenericMatch = normalized.match(APPLE_GENERIC_NAME_PATTERN);
  if (appleGenericMatch && appleGenericMatch[1]?.trim().toLowerCase() === ip.trim().toLowerCase()) {
    return true;
  }

  return SLUG_ONLY_PATTERN.test(normalized) && normalized.endsWith(`-${dashedIp}`);
}

export function looksLikeScannedDeviceName(device: Pick<Device, "name" | "ip" | "metadata">): boolean {
  const identity = isRecord(device.metadata?.identity) ? device.metadata.identity : null;
  if (identity?.nameManuallySet === true) {
    return false;
  }

  return isAutoGeneratedDeviceName(device.name, device.ip);
}

export function getDeviceIdentityDescription(device: Pick<Device, "metadata">): string {
  if (!isRecord(device.metadata)) {
    return "";
  }

  const identity = isRecord(device.metadata.identity) ? device.metadata.identity : null;
  if (identity && typeof identity.description === "string" && identity.description.trim().length > 0) {
    return identity.description.trim();
  }

  const adoption = isRecord(device.metadata.adoption) ? device.metadata.adoption : null;
  if (adoption && typeof adoption.profileSummary === "string" && adoption.profileSummary.trim().length > 0) {
    return adoption.profileSummary.trim();
  }

  return "";
}
