import type { RuntimeSettings } from "@/lib/state/types";

export const defaultRuntimeSettings = (): RuntimeSettings => ({
  scannerIntervalMs: 120_000,
  agentWakeIntervalMs: 10 * 60 * 1000,
  deepScanIntervalMs: 30 * 60 * 1000,
  incrementalActiveTargets: 32,
  deepActiveTargets: 256,
  incrementalPortScanHosts: 16,
  deepPortScanHosts: 96,
  llmDiscoveryLimit: 10,
  incrementalFingerprintTargets: 16,
  deepFingerprintTargets: 96,
  enableMdnsDiscovery: true,
  enableSsdpDiscovery: true,
  enableSnmpProbe: true,
  enableAdvancedNmapFingerprint: true,
  nmapFingerprintTimeoutMs: 30_000,
  incrementalNmapTargets: 8,
  deepNmapTargets: 48,
  enablePacketIntel: true,
  packetIntelDurationSec: 5,
  packetIntelMaxPackets: 2_500,
  packetIntelTopTalkers: 12,
  enableBrowserObservation: true,
  browserObservationTimeoutMs: 12_000,
  incrementalBrowserObservationTargets: 6,
  deepBrowserObservationTargets: 32,
  browserObservationCaptureScreenshots: false,
  enableWebResearch: true,
  webResearchProvider: "brave_scrape",
  webResearchFallbackStrategy: "prefer_non_key",
  webResearchTimeoutMs: 18_000,
  webResearchMaxResults: 10,
  webResearchDeepReadPages: 3,
  enableDhcpLeaseIntel: true,
  dhcpLeaseCommandTimeoutMs: 6_000,
  ouiUpdateIntervalMs: 7 * 24 * 60 * 60 * 1000,
  laneBEnabled: false,
  laneBAllowedEnvironments: ["lab", "dev"],
  laneBAllowedFamilies: ["service-recovery", "disk-cleanup", "backup-retry"],
  laneCMutationsInLab: false,
  laneCMutationsInProd: false,
  mutationRequireDryRunWhenSupported: true,
  approvalTtlClassBMs: 2 * 60 * 60 * 1000,
  approvalTtlClassCMs: 60 * 60 * 1000,
  approvalTtlClassDMs: 30 * 60 * 1000,
  quarantineThresholdCount: 3,
  quarantineThresholdWindowMs: 10 * 60 * 1000,
  availabilityScannerAlertsEnabled: true,
  securityScannerAlertsEnabled: true,
  serviceContractScannerAlertsEnabled: true,
  ignoredIncidentTypes: [],
  localToolInstallPolicy: "require_approval",
  localToolExecutionPolicy: "require_approval",
  localToolApprovalTtlMs: 60 * 60 * 1000,
  localToolHealthCheckIntervalMs: 6 * 60 * 60 * 1000,
  localToolAutoInstallBuiltins: false,
  protocolSessionSweepIntervalMs: 15_000,
  protocolSessionDefaultLeaseTtlMs: 5 * 60 * 1000,
  protocolSessionMaxLeaseTtlMs: 24 * 60 * 60 * 1000,
  protocolSessionMessageRetentionLimit: 250,
  protocolSessionReconnectBaseMs: 1_000,
  protocolSessionReconnectMaxMs: 60_000,
});
